# Header
menu:
  Home: /
  Archives: /archives

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: This is Phantom, a free, fully responsive site<br />template designed by <a href="http://html5up.net">HTML5 UP</a>.

# Theme Secondary subtitle
susbtitle_secondary: Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.

# Footer About Section
about_footer: This theme was initially developed by HTML5 Templates and adapted for Hexo by Jonathan Klughertz.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: sdfsd
facebook_url: https://www.facebook.com/
instagram_url: sdfsdf
dribble_url: https://dribbble.com/pixelhint
github_url: sdfsdf
googleplus_url: https://plus.google.com/+Pixelhint/posts
behance_url: https://www.behance.net/
fivehundredpx_url: sdfsdf
email_url: sdfsdfs
rss_url: sdfsdf
