# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: This is Phantom, a free, fully responsive site<br />template designed by <a href="http://html5up.net">HTML5 UP</a>.

# Theme Secondary subtitle
susbtitle_secondary: Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.

# Footer About Section
about_footer: This theme was initially developed by <a href="http://html5up.net" target="_blank">HTML5 UP</a>. It is adapted for Hexo by <a href="http://www.codeblocq.com/" target="_blank">Jonathan Klughertz</a>.<br />The source code is available on <a href="https://github.com/klugjo/hexo-theme-phantom" target="_blank">GitHub</a>.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/hexo-theme-phantom/commits?author=klugjo
googleplus_url: https://plus.google.com/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: \#
rss_url: \#
